'use client';
import { Outfit } from 'next/font/google';
import './globals.css';
import Header from './_components/Header';
import { usePathname } from 'next/navigation';
import { AuthContextProvider } from './context/AuthContext';

const outfit = Outfit({ subsets: ['latin'] });

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const params = usePathname();
  const showHeader = params == '/login' || params == '/sign-up' ? false : true;
  return (
    <html lang="en">
      <AuthContextProvider>
        <body className={outfit.className}>
          {showHeader ? <Header /> : null}
          {children}
        </body>
      </AuthContextProvider>
    </html>
  );
}
