"use client";
import { Outfit } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import Header from "./_components/Header";

const outfit = Outfit({ subsets: ['latin'] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const params = usePathname();
  const showHeader = params == "/login" ? false : true;
  return (
    <html lang="en">
      <body className={outfit.className}>
        {showHeader ? <Header /> : null}
        {children}
      </body>
    </html>
  );
} 
